/**
 * Comedy-Connections
 *
 * Copyright (c) 2012 Steven Blair
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

var Data = {
    show: [
        {id: 1, type: "TV", title: "Black Books", year: 2000},
        {id: 2, type: "TV", title: "Look Around You", year: 2001},
        {id: 3, type: "TV", title: "I'm Alan Partridge", year: 1997},
        {id: 4, type: "TV", title: "Knowing Me, Knowing You", year: 1994},
        {id: 5, type: "TV", title: "Skins", year: 2007},
        {id: 6, type: "TV", title: "The Fast Show", year: 1999},
        {id: 7, type: "TV", title: "Peep Show", year: 2003},
        {id: 8, type: "TV", title: "Green Wing", year: 2003},
        {id: 9, type: "TV", title: "Is It Bill Bailey?", year: 1998},
        {id: 10, type: "TV", title: "The Office", year: 2001},
        {id: 11, type: "TV", title: "Extras", year: 2005},
        {id: 12, type: "TV", title: "The Thick of It", year: 2005},
        {id: 13, type: "TV", title: "That Mitchell and Webb Look", year: 2006},
        {id: 14, type: "TV", title: "Still Game", year: 2002},
        {id: 15, type: "TV", title: "Chewin' the Fat", year: 1999},
        {id: 16, type: "TV", title: "Saxondale", year: 2006},
        {id: 17, type: "TV", title: "Rab C. Nesbitt", year: 1988},
        {id: 18, type: "TV", title: "The Mighty Boosh", year: 2004},
        {id: 19, type: "TV", title: "Garth Marenghi's Darkplace", year: 2004},
        {id: 20, type: "TV", title: "Big Train", year: 1998},
        {id: 21, type: "TV", title: "The Day Today", year: 1994},
        {id: 22, type: "TV", title: "The IT Crowd", year: 2006},
        {id: 23, type: "TV", title: "Father Ted", year: 1995},
        {id: 24, type: "TV", title: "Black Adder", year: 1995},
        {id: 25, type: "TV", title: "Arrested Development", year: 2003},
        {id: 26, type: "TV", title: "Spaced", year: 1999},
        {id: 27, type: "Film", title: "Shaun of the Dead", year: 2003},
        {id: 28, type: "Film", title: "Hot Fuzz", year: 2007},
        {id: 29, type: "Film", title: "Run, Fat Boy, Run", year: 2007},
        {id: 30, type: "TV", title: "Coupling", year: 2000},
        {id: 31, type: "Film", title: "In the Loop", year: 2009},
        {id: 32, type: "Film", title: "A Cock and Bull Story", year: 2005},
        {id: 33, type: "Film", title: "Saving Grace", year: 2000},
        {id: 34, type: "Film", title: "Scoop", year: 2006},
        {id: 35, type: "Film", title: "Magicians", year: 2007},
        {id: 36, type: "Film", title: "The Invention of Lying", year: 2009},
        {id: 37, type: "TV", title: "Jonathon Creek", year: 1997},
        {id: 38, type: "TV", title: "Brass Eye", year: 1997},
        {id: 39, type: "Film", title: "Kinky Boots", year: 2005},
        {id: 40, type: "TV", title: "Smack the Pony", year: 1999},
        {id: 41, type: "TV", title: "South Park", year: 1997},
        {id: 42, type: "Film", title: "The Hitchhiker's Guide to the Galaxy", year: 2005},
        {id: 43, type: "TV", title: "Red Dwarf", year: 1988},
        {id: 44, type: "TV", title: "Curb Your Enthusiasm", year: 2000},
        {id: 45, type: "TV", title: "Mystery Science Theater 3000", year: 1990},
        {id: 46, type: "TV", title: "Spitting Image", year: 1984},
        {id: 47, type: "TV", title: "Saxondale", year: 2006},
        {id: 48, type: "TV", title: "Little Britain", year: 2003},
        {id: 49, type: "TV", title: "The Peter Serafinowicz Show", year: 2007},
        //{id: 56, type: "TV", title: "The Inbetweeners", year: 2008},
        {id: 50, type: "TV", title: "Not the Nine O'Clock News", year: 1979},
        {id: 51, type: "TV", title: "Mr Bean", year: 1990},
        {id: 52, type: "TV", title: "Jeeves and Wooster", year: 1990},
        {id: 53, type: "TV", title: "House", year: 2004},
        {id: 54, type: "TV", title: "Time Trumpet", year: 2006},
        {id: 55, type: "TV", title: "Jam", year: 2000},
        {id: 56, type: "TV", title: "Little Britain", year: 2003}
    ],
    person: [
        {id: 1, name: "Bill Bailey", dob: 1964},
        {id: 2, name: "Simon Pegg", dob: 1970},
        {id: 3, name: "Nick Frost", dob: 1972},
        {id: 4, name: "Peter Serafinowicz", dob: 1972},
        {id: 5, name: "Robert Popper", dob: 1972},          // todo: verify DOB
        {id: 6, name: "Sarah Alexander", dob: 1971},
        {id: 7, name: "Dylan Moran", dob: 1971},
        {id: 8, name: "Steve Coogan", dob: 1965},
        {id: 9, name: "Rob Brydon", dob: 1965},
        {id: 10, name: "Mark Heap", dob: 1957},
        {id: 11, name: "Tamsin Greig", dob: 1967},
        {id: 12, name: "David Mitchell", dob: 1974},
        {id: 13, name: "Robert Webb", dob: 1972},
        {id: 14, name: "Olivia Colman", dob: 1974},
        {id: 15, name: "Ricky Gervais", dob: 1961},
        {id: 16, name: "Peter Capaldi", dob: 1958},
        {id: 17, name: "Gregor Fisher", dob: 1953},
        {id: 18, name: "Ashley Jensen", dob: 1969},
        {id: 19, name: "Karen Dunbar", dob: 1971},
        {id: 20, name: "Ford Kiernan", dob: 1962},
        {id: 21, name: "Greg Hemphill", dob: 1969},
        {id: 22, name: "Chris Morris", dob: 1971},
        {id: 23, name: "Simon Day", dob: 1962},
        {id: 24, name: "Mark Williams", dob: 1959},
        {id: 25, name: "James Bachman", dob: 1972},
        {id: 26, name: "Julian Barratt", dob: 1968},
        {id: 27, name: "Noel Fielding", dob: 1973},
        {id: 28, name: "Matthew Holness", dob: 1974},          // todo: verify DOB
        {id: 29, name: "Richard Ayoade", dob: 1977},
        {id: 30, name: "Adam Buxton", dob: 1969},
        {id: 31, name: "Graham Lineham", dob: 1968},
        {id: 32, name: "David Schneider", dob: 1963},
        {id: 33, name: "Ardal O'Hanlon", dob: 1965},
        {id: 34, name: "Rowan Atkinson", dob: 1965},
        {id: 35, name: "Stephen Fry", dob: 1957},
        {id: 36, name: "Hugh Laurie", dob: 1959},
        {id: 37, name: "Chris Addison", dob: 1971},
        {id: 38, name: "Kevin Eldon", dob: 1960},
        {id: 39, name: "Jason Bateman", dob: 1969},
        {id: 40, name: "Rebecca Front", dob: 1964},
        {id: 41, name: "Jessica Hynes", dob: 1972},
        {id: 42, name: "Martin Freeman", dob: 1971},
        {id: 43, name: "Stephen Merchant", dob: 1974},
        {id: 44, name: "Matt Lucas", dob: 1974},
        {id: 45, name: "David Walliams", dob: 1971}
    ],
    personToShow: [
        {personId: 1, showId: 1},
        {personId: 1, showId: 5},
        {personId: 1, showId: 9},
        {personId: 1, showId: 26},
        {personId: 1, showId: 28},
        {personId: 1, showId: 29},
        {personId: 1, showId: 42},
        {personId: 1, showId: 33},
        {personId: 1, showId: 37},
        {personId: 2, showId: 26},
        {personId: 2, showId: 1},
        {personId: 2, showId: 27},
        {personId: 2, showId: 20},
        {personId: 2, showId: 9},
        {personId: 2, showId: 3},
        {personId: 2, showId: 38},
        {personId: 2, showId: 2},
        {personId: 2, showId: 28},
        {personId: 2, showId: 29},
        {personId: 3, showId: 26},
        {personId: 3, showId: 1},
        {personId: 3, showId: 27},
        {personId: 3, showId: 20},
        {personId: 3, showId: 2},
        {personId: 3, showId: 8},
        {personId: 3, showId: 28},
        {personId: 3, showId: 39},
        {personId: 4, showId: 2},
        {personId: 4, showId: 26},
        {personId: 4, showId: 1},
        {personId: 4, showId: 3},
        {personId: 4, showId: 40},
        {personId: 4, showId: 41},
        {personId: 4, showId: 27},
        {personId: 4, showId: 29},
        {personId: 4, showId: 22},
        {personId: 4, showId: 49},
        {personId: 5, showId: 7},
        {personId: 5, showId: 2},
        {personId: 5, showId: 26},
        {personId: 5, showId: 27},
        {personId: 5, showId: 28},
        {personId: 6, showId: 2},
        {personId: 6, showId: 30},
        {personId: 6, showId: 8},
        {personId: 6, showId: 43},
        {personId: 6, showId: 40},
        {personId: 6, showId: 27},
        {personId: 6, showId: 29},
        {personId: 6, showId: 22},
        {personId: 7, showId: 1},
        {personId: 7, showId: 27},
        {personId: 7, showId: 32},
        {personId: 7, showId: 29},
        {personId: 8, showId: 3},
        {personId: 8, showId: 4},
        {personId: 8, showId: 46},
        {personId: 8, showId: 21},
        {personId: 8, showId: 47},
        {personId: 8, showId: 48},
        {personId: 8, showId: 32},
        {personId: 8, showId: 28},
        {personId: 8, showId: 31},
        {personId: 8, showId: 44},
        {personId: 9, showId: 11},
        {personId: 9, showId: 27},
        {personId: 9, showId: 3},
        {personId: 9, showId: 1},
        {personId: 10, showId: 2},
        {personId: 10, showId: 26},
        {personId: 10, showId: 8},
        {personId: 10, showId: 20},
        {personId: 10, showId: 38},
        {personId: 10, showId: 5},
        {personId: 10, showId: 34},
        {personId: 10, showId: 55},
        {personId: 11, showId: 1},
        {personId: 11, showId: 8},
        {personId: 11, showId: 27},
        {personId: 12, showId: 7},
        {personId: 12, showId: 13},
        {personId: 12, showId: 2},
        {personId: 12, showId: 35},
        {personId: 13, showId: 7},
        {personId: 13, showId: 13},
        {personId: 13, showId: 35},
        {personId: 14, showId: 7},
        {personId: 14, showId: 13},
        {personId: 14, showId: 35},
        {personId: 14, showId: 2},
        {personId: 14, showId: 28},
        {personId: 14, showId: 10},
        {personId: 14, showId: 1},
        {personId: 14, showId: 8},
        {personId: 14, showId: 5},
        {personId: 15, showId: 10},
        {personId: 15, showId: 11},
        {personId: 15, showId: 36},
        {personId: 16, showId: 12},
        {personId: 16, showId: 31},
        {personId: 16, showId: 7},
        {personId: 16, showId: 35},
        {personId: 16, showId: 5},
        {personId: 16, showId: 17},
        {personId: 17, showId: 17},
        {personId: 18, showId: 17},
        {personId: 18, showId: 10},
        {personId: 18, showId: 11},
        {personId: 18, showId: 32},
        {personId: 19, showId: 17},
        {personId: 19, showId: 15},
        {personId: 20, showId: 14},
        {personId: 20, showId: 15},
        {personId: 20, showId: 17},
        {personId: 20, showId: 9},
        {personId: 21, showId: 14},
        {personId: 21, showId: 15},
        {personId: 21, showId: 17},
        {personId: 22, showId: 38},
        {personId: 22, showId: 21},
        {personId: 22, showId: 20},
        {personId: 22, showId: 3},
        {personId: 22, showId: 22},
        {personId: 22, showId: 55},
        {personId: 23, showId: 6},
        {personId: 23, showId: 5},
        {personId: 23, showId: 29},
        {personId: 24, showId: 6},
        {personId: 24, showId: 47},
        {personId: 24, showId: 32},
        {personId: 24, showId: 43},
        {personId: 25, showId: 7},
        {personId: 25, showId: 13},
        {personId: 25, showId: 47},
        {personId: 25, showId: 22},
        {personId: 25, showId: 35},
        {personId: 25, showId: 18},
        {personId: 26, showId: 2},
        {personId: 26, showId: 18},
        {personId: 26, showId: 19},
        {personId: 27, showId: 18},
        {personId: 27, showId: 19},
        {personId: 27, showId: 22},
        {personId: 28, showId: 10},
        {personId: 28, showId: 19},
        {personId: 28, showId: 54},
        {personId: 38, showId: 55},
        {personId: 29, showId: 19},
        {personId: 29, showId: 22},
        {personId: 29, showId: 18},
        {personId: 29, showId: 54},
        {personId: 30, showId: 28},
        {personId: 30, showId: 22},
        {personId: 30, showId: 1},
        {personId: 30, showId: 54},
        {personId: 31, showId: 22},
        {personId: 31, showId: 1},
        {personId: 31, showId: 20},
        {personId: 31, showId: 19},
        {personId: 31, showId: 3},
        {personId: 31, showId: 21},
        {personId: 31, showId: 23},
        {personId: 32, showId: 2},
        {personId: 32, showId: 34},
        {personId: 32, showId: 3},
        {personId: 32, showId: 4},
        {personId: 32, showId: 21},
        {personId: 32, showId: 51},
        {personId: 33, showId: 23},
        {personId: 33, showId: 5},
        {personId: 34, showId: 24},
        {personId: 34, showId: 51},
        {personId: 34, showId: 50},
        {personId: 35, showId: 24},
        {personId: 35, showId: 32},
        {personId: 35, showId: 42},
        {personId: 35, showId: 52},
        {personId: 36, showId: 24},
        {personId: 36, showId: 53},
        {personId: 36, showId: 52},
        {personId: 37, showId: 5},
        {personId: 37, showId: 12},
        {personId: 37, showId: 21},
        {personId: 38, showId: 3},
        {personId: 38, showId: 4},
        {personId: 38, showId: 38},
        {personId: 38, showId: 1},
        {personId: 38, showId: 26},
        {personId: 38, showId: 20},
        {personId: 38, showId: 40},
        {personId: 38, showId: 8},
        {personId: 38, showId: 2},
        {personId: 38, showId: 28},
        {personId: 38, showId: 16},
        {personId: 38, showId: 5},
        {personId: 39, showId: 25},
        {personId: 39, showId: 36},
        {personId: 40, showId: 12},
        {personId: 40, showId: 21},
        {personId: 40, showId: 37},
        {personId: 40, showId: 3},
        {personId: 40, showId: 20},
        {personId: 41, showId: 26},
        {personId: 41, showId: 5},
        {personId: 41, showId: 35},
        {personId: 41, showId: 1},
        {personId: 42, showId: 10},
        {personId: 42, showId: 27},
        {personId: 42, showId: 28},
        {personId: 42, showId: 42},
        {personId: 43, showId: 10},
        {personId: 43, showId: 11},
        {personId: 43, showId: 28},
        {personId: 43, showId: 29},
        {personId: 43, showId: 36},
        {personId: 43, showId: 8},
        {personId: 43, showId: 19},
        {personId: 44, showId: 2},
        {personId: 44, showId: 27},
        {personId: 44, showId: 56},
        {personId: 45, showId: 56},
        {personId: 45, showId: 1},
        {personId: 45, showId: 2},
        {personId: 45, showId: 26},
        {personId: 45, showId: 29},
        {personId: 45, showId: 27},
        {personId: 45, showId: 32}
    ]
}
