// Browser version of traer.pde and ComedyConnections.pde.

// Traer Physics 3.0
// Terms from Traer's download page, http://traer.cc/mainsite/physics/
//   LICENSE - Use this code for whatever you want, just send me a link jeff@traer.cc
//
// traer3a.pde
//   From traer.physics - author: Jeff Traer
//     Attraction              Particle
//     EulerIntegrator         ParticleSystem
//     Force                   RungeKuttaIntegrator
//     Integrator              Spring
//     ModifiedEulerIntegrator Vector3D
//
//   From traer.animator - author: Jeff Traer
//     Smoother
//     Smoother3D
//     Tickable
//
//   New - author: Carl Pearson
//     UniversalAttraction
//     Pulse
//

// 13 Dec 2010: Copied 3.0 src from http://traer.cc/mainsite/physics/ and ported to Processingjs,
//              added makeParticle2(), makeAttraction2(), replaceAttraction(), and removeParticle(int) -mrn (Mike Niemi)
//  9 Feb 2011: Fixed bug in Euler integrators where they divided by time instead of
//              multiplying by it in the update steps,
//              eliminated the Vector3D class (converting the code to use the native PVector class),
//              did some code compaction in the RK solver,
//              added a couple convenience classes, UniversalAttraction and Pulse, simplifying
//              the Pendulums sample (renamed to dynamics.pde) considerably. -cap (Carl Pearson)

/**
 * Comedy-Connections
 *
 * Copyright (c) 2012 Steven Blair
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


var comedyConnectionsSketch = ((function(Sketch) {
var sketch = new Sketch(
// this code was autogenerated from PJS
(function($p) {
var Force = (function() {
function Force() { throw 'Unable to create the interface'; }
Force.$isInterface = true;
Force.$methods = ['turnOn', 'turnOff', 'isOn', 'isOff', 'apply'];
return Force;
})();
$p.Force = Force;
var Integrator = (function() {
function Integrator() { throw 'Unable to create the interface'; }
Integrator.$isInterface = true;
Integrator.$methods = ['step'];
return Integrator;
})();
$p.Integrator = Integrator;
var Tickable = (function() {
function Tickable() { throw 'Unable to create the interface'; }
Tickable.$isInterface = true;
Tickable.$methods = ['tick', 'setSmoothness'];
return Tickable;
})();
$p.Tickable = Tickable;
var Item = (function() {
function Item() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.id = 0;
$this_1.name = null;
$this_1.selected =  true;
$this_1.hovered =  false;
function visible$0() {
if ($this_1.hovered || $this_1.selected) {
return true;
}

        return false;
}
$p.addMethod($this_1, 'visible', visible$0, false);
function $constr() {
$superCstr();
}
$constr.apply(null, arguments);
}
return Item;
})();
$p.Item = Item;
var Edge = (function() {
function Edge() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.item = null;
$this_1.vertexA = null;
$this_1.vertexB = null;
function $constr_3(i, a, b){
$superCstr();

$this_1.item = i;
        $this_1.vertexA = a;
        $this_1.vertexB = b;

        $this_1.vertexA.addEdge($this_1.$self);
        $this_1.vertexB.addEdge($this_1.$self);
}

function $constr() {
if(arguments.length === 3) { $constr_3.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
return Edge;
})();
$p.Edge = Edge;
var Attraction = (function() {
function Attraction() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.one = null;
$this_1.b = null;
$this_1.k = 0;
$this_1.on =  true;
$this_1.distanceMin = 0;
$this_1.distanceMinSquared = 0;
function setA$1(p) {
$this_1.one = p;
}
$p.addMethod($this_1, 'setA', setA$1, false);
function setB$1(p) {
$this_1.b = p;
}
$p.addMethod($this_1, 'setB', setB$1, false);
function getMinimumDistance$0() {
return $this_1.distanceMin;
}
$p.addMethod($this_1, 'getMinimumDistance', getMinimumDistance$0, false);
function setMinimumDistance$1(d) {
$this_1.distanceMin = d; $this_1.distanceMinSquared = d*d;
}
$p.addMethod($this_1, 'setMinimumDistance', setMinimumDistance$1, false);
function turnOff$0() {
$this_1.on = false;
}
$p.addMethod($this_1, 'turnOff', turnOff$0, false);
function turnOn$0() {
$this_1.on = true;
}
$p.addMethod($this_1, 'turnOn', turnOn$0, false);
function setStrength$1(k) {
$this_1.k = k;
}
$p.addMethod($this_1, 'setStrength', setStrength$1, false);
function getOneEnd$0() {
return $this_1.one;
}
$p.addMethod($this_1, 'getOneEnd', getOneEnd$0, false);
function getTheOtherEnd$0() {
return $this_1.b;
}
$p.addMethod($this_1, 'getTheOtherEnd', getTheOtherEnd$0, false);
function apply$0() {
if ( $this_1.on && ( $this_1.one.isFree() || $this_1.b.isFree() ) )
      {
var dx =  $this_1.one.position.x - $this_1.b.position.x;
        var dy =  $this_1.one.position.y - $this_1.b.position.y;
        var dz =  $this_1.one.position.z - $this_1.b.position.z;
        var distanceSquared =  dx * dx + dy * dy + dz * dz;
        if (distanceSquared < $this_1.distanceMinSquared) distanceSquared = $this_1.distanceMinSquared;
        var force =  $this_1.k * $this_1.one.mass0 * $this_1.b.mass0 / (distanceSquared * Math.sqrt(distanceSquared));
        dx *= force;
        dy *= force;
        dz *= force;

        if ( $this_1.b.isFree() ) {
$this_1.b.force.x += dx;
          $this_1.b.force.y += dy;
          $this_1.b.force.z += dz;
}
        if ( $this_1.one.isFree() ) {
$this_1.one.force.x += dx * -1;
          $this_1.one.force.y += dy * -1;
          $this_1.one.force.z += dz * -1;
}
}
}
$p.addMethod($this_1, 'apply', apply$0, false);
function getStrength$0() {
return $this_1.k;
}
$p.addMethod($this_1, 'getStrength', getStrength$0, false);
function isOn$0() {
return $this_1.on;
}
$p.addMethod($this_1, 'isOn', isOn$0, false);
function isOff$0() {
return !$this_1.on;
}
$p.addMethod($this_1, 'isOff', isOff$0, false);
function $constr_4(a, b, k, distanceMin){
$superCstr();

$this_1.one = a;
    $this_1.b = b;
    $this_1.k = k;
    $this_1.distanceMin = distanceMin;
    $this_1.distanceMinSquared = distanceMin*distanceMin;
}

function $constr() {
if(arguments.length === 4) { $constr_4.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(Attraction, Force);
Attraction.$interfaces = [Force];
return Attraction;
})();
$p.Attraction = Attraction;
var UniversalAttraction = (function() {
function UniversalAttraction() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.k = 0;
$this_1.on =  true;
$this_1.distanceMin = 0;
$this_1.distanceMinSquared = 0;
$this_1.targetList = null;
function getMinimumDistance$0() {
return $this_1.distanceMin;
}
$p.addMethod($this_1, 'getMinimumDistance', getMinimumDistance$0, false);
function setMinimumDistance$1(d) {
$this_1.distanceMin = d; $this_1.distanceMinSquared = d*d;
}
$p.addMethod($this_1, 'setMinimumDistance', setMinimumDistance$1, false);
function turnOff$0() {
$this_1.on = false;
}
$p.addMethod($this_1, 'turnOff', turnOff$0, false);
function turnOn$0() {
$this_1.on = true;
}
$p.addMethod($this_1, 'turnOn', turnOn$0, false);
function setStrength$1(k) {
$this_1.k = k;
}
$p.addMethod($this_1, 'setStrength', setStrength$1, false);
function getStrength$0() {
return $this_1.k;
}
$p.addMethod($this_1, 'getStrength', getStrength$0, false);
function isOn$0() {
return $this_1.on;
}
$p.addMethod($this_1, 'isOn', isOn$0, false);
function isOff$0() {
return !$this_1.on;
}
$p.addMethod($this_1, 'isOff', isOff$0, false);
function apply$0() {
if ( $this_1.on ) {
for (var i = 0;  i < $this_1.targetList.size();  i++ ) {
for (var j = i+1;  j < $this_1.targetList.size();  j++) {
var a =  $this_1.targetList.get(i);
            var b =  $this_1.targetList.get(j);
            if ( a.isFree() || b.isFree() ) {
var a2b =  $p.PVector.sub(a.position, b.position, new $p.PVector());
              var a2bDistanceSquared =  a2b.dot(a2b);
              if ( a2bDistanceSquared < $this_1.distanceMinSquared )
              a2bDistanceSquared = $this_1.distanceMinSquared;
              var force =  $this_1.k * a.mass0 * b.mass0 / (a2bDistanceSquared * Math.sqrt(a2bDistanceSquared));
              a2b.mult( force );

              if ( b.isFree() ) b.force.add( a2b );
              if ( a.isFree() ) {
a2b.mult(-1);
                 a.force.add( a2b );
}
}
}
}
}
}
$p.addMethod($this_1, 'apply', apply$0, false);
function $constr_3(k, distanceMin, targetList){
$superCstr();

$this_1.k = k;
    $this_1.distanceMin = distanceMin;
    $this_1.distanceMinSquared = distanceMin*distanceMin;
    $this_1.targetList = targetList;
}

function $constr() {
if(arguments.length === 3) { $constr_3.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(UniversalAttraction, Force);
UniversalAttraction.$interfaces = [Force];
return UniversalAttraction;
})();
$p.UniversalAttraction = UniversalAttraction;
var Pulse = (function() {
function Pulse() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.k = 0;
$this_1.on =  true;
$this_1.distanceMin = 0;
$this_1.distanceMinSquared = 0;
$this_1.lifetime = 0;
$this_1.origin = null;
$this_1.targetList = null;
function turnOff$0() {
$this_1.on = false;
}
$p.addMethod($this_1, 'turnOff', turnOff$0, false);
function turnOn$0() {
$this_1.on = true;
}
$p.addMethod($this_1, 'turnOn', turnOn$0, false);
function isOn$0() {
return $this_1.on;
}
$p.addMethod($this_1, 'isOn', isOn$0, false);
function isOff$0() {
return !$this_1.on;
}
$p.addMethod($this_1, 'isOff', isOff$0, false);
function tick$1(time) {
$this_1.lifetime-=time;
    if ($this_1.lifetime <= 0) $this_1.$self.turnOff();
    return $this_1.on;
}
$p.addMethod($this_1, 'tick', tick$1, false);
function apply$0() {
if ($this_1.on) {
var holder =  new $p.PVector();
      var count =  0;
      for (var i =  $this_1.targetList.iterator();  i.hasNext();  ) {
var p =  i.next();
        if ( p.isFree() ) {
holder.set( p.position.x, p.position.y, p.position.z );
          holder.sub( $this_1.origin );
          var distanceSquared =  holder.dot(holder);
          if (distanceSquared < $this_1.distanceMinSquared) distanceSquared = $this_1.distanceMinSquared;
          holder.mult($this_1.k / (distanceSquared * Math.sqrt(distanceSquared)) );
          p.force.add( holder );
}
}
}
}
$p.addMethod($this_1, 'apply', apply$0, false);
function $constr_5(k, distanceMin, origin, lifetime, targetList){
$superCstr();

$this_1.k = k;
    $this_1.distanceMin = distanceMin;
    $this_1.distanceMinSquared = distanceMin*distanceMin;
    $this_1.origin = origin;
    $this_1.targetList = targetList;
    $this_1.lifetime = lifetime;
}

function $constr() {
if(arguments.length === 5) { $constr_5.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(Pulse, Force);
Pulse.$interfaces = [Force];
return Pulse;
})();
$p.Pulse = Pulse;
var EulerIntegrator = (function() {
function EulerIntegrator() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.s = null;
function step$1(t) {
$this_1.s.clearForces();
    $this_1.s.applyForces();

    for (var i =  $this_1.s.particles.iterator();  i.hasNext();  )
      {
var p =  i.next();
  if ( p.isFree() )
          {
p.velocity.add( $p.PVector.mult(p.force, t/p.mass0) );
      p.position.add( $p.PVector.mult(p.velocity, t) );
}
}
}
$p.addMethod($this_1, 'step', step$1, false);
function $constr_1(s){
$superCstr();

$this_1.s = s;
}

function $constr() {
if(arguments.length === 1) { $constr_1.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(EulerIntegrator, Integrator);
EulerIntegrator.$interfaces = [Integrator];
return EulerIntegrator;
})();
$p.EulerIntegrator = EulerIntegrator;
var ModifiedEulerIntegrator = (function() {
function ModifiedEulerIntegrator() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.s = null;
function step$1(t) {
$this_1.s.clearForces();
    $this_1.s.applyForces();

    var halft =  0.5*t;
    var a =  new $p.PVector();
    var holder =  new $p.PVector();
    for (var i =  0;  i < $this_1.s.numberOfParticles();  i++ )
      {
var p =  $this_1.s.getParticle( i );
  if ( p.isFree() )
    {
$p.PVector.div(p.force, p.mass0, a);
      p.position.add( $p.PVector.mult(p.velocity, t, holder) );
            p.velocity.add( $p.PVector.mult(a, t, a) );
      p.position.add( $p.PVector.mult(a, halft, a) );
}
}
}
$p.addMethod($this_1, 'step', step$1, false);
function $constr_1(s){
$superCstr();

$this_1.s = s;
}

function $constr() {
if(arguments.length === 1) { $constr_1.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(ModifiedEulerIntegrator, Integrator);
ModifiedEulerIntegrator.$interfaces = [Integrator];
return ModifiedEulerIntegrator;
})();
$p.ModifiedEulerIntegrator = ModifiedEulerIntegrator;
var Particle = (function() {
function Particle() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.position =  new $p.PVector();
$this_1.velocity =  new $p.PVector();
$this_1.force =  new $p.PVector();
$this_1.mass0 = 0;
$this_1.age0 =  0;
$this_1.dead0 =  false;
$this_1.fixed0 =  false;
function distanceTo$1(p) {
return $this_1.position.dist( p.position );
}
$p.addMethod($this_1, 'distanceTo', distanceTo$1, false);
function makeFixed$0() {
$this_1.fixed0 = true;
    $this_1.velocity.set(0,0,0);
    $this_1.force.set(0, 0, 0);
    return $this_1.$self;
}
$p.addMethod($this_1, 'makeFixed', makeFixed$0, false);
function makeFree$0() {
$this_1.fixed0 = false;
    return $this_1.$self;
}
$p.addMethod($this_1, 'makeFree', makeFree$0, false);
function isFixed$0() {
return $this_1.fixed0;
}
$p.addMethod($this_1, 'isFixed', isFixed$0, false);
function isFree$0() {
return !$this_1.fixed0;
}
$p.addMethod($this_1, 'isFree', isFree$0, false);
function mass$0() {
return $this_1.mass0;
}
$p.addMethod($this_1, 'mass', mass$0, false);
function setMass$1(m) {
$this_1.mass0 = m;
}
$p.addMethod($this_1, 'setMass', setMass$1, false);
function age$0() {
return $this_1.age0;
}
$p.addMethod($this_1, 'age', age$0, false);
function reset$0() {
$this_1.age0 = 0;
    $this_1.dead0 = false;
    $this_1.position.set(0,0,0);
    $this_1.velocity.set(0,0,0);
    $this_1.force.set(0,0,0);
    $this_1.mass0 = 1;
}
$p.addMethod($this_1, 'reset', reset$0, false);
function $constr_1(m){
$superCstr();

$this_1.mass0 = m;
}

function $constr() {
if(arguments.length === 1) { $constr_1.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
return Particle;
})();
$p.Particle = Particle;
var ParticleSystem = (function() {
function ParticleSystem() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$p.defineProperty($this_1, 'RUNGE_KUTTA', {get: function(){return ParticleSystem.RUNGE_KUTTA}, set: function(val){ParticleSystem.RUNGE_KUTTA = val}});
$p.defineProperty($this_1, 'MODIFIED_EULER', {get: function(){return ParticleSystem.MODIFIED_EULER}, set: function(val){ParticleSystem.MODIFIED_EULER = val}});
$p.defineProperty($this_1, 'DEFAULT_GRAVITY', {get: function(){return ParticleSystem.DEFAULT_GRAVITY}, set: function(val){ParticleSystem.DEFAULT_GRAVITY = val}});
$p.defineProperty($this_1, 'DEFAULT_DRAG', {get: function(){return ParticleSystem.DEFAULT_DRAG}, set: function(val){ParticleSystem.DEFAULT_DRAG = val}});
$this_1.particles =  new $p.ArrayList();
$this_1.springs =  new $p.ArrayList();
$this_1.attractions =  new $p.ArrayList();
$this_1.customForces =  new $p.ArrayList();
$this_1.pulses =  new $p.ArrayList();
$this_1.integrator = null;
$this_1.gravity =  new $p.PVector();
$this_1.drag = 0;
$this_1.hasDeadParticles =  false;
function setIntegrator$1(which) {
switch ( which )
    {
case ParticleSystem.RUNGE_KUTTA:
  $this_1.integrator = new RungeKuttaIntegrator( $this_1.$self );
  break;case ParticleSystem.MODIFIED_EULER:
  $this_1.integrator = new ModifiedEulerIntegrator( $this_1.$self );
  break;
}
}
$p.addMethod($this_1, 'setIntegrator', setIntegrator$1, false);
function setGravity$3(x, y, z) {
$this_1.gravity.set( x, y, z );
}
$p.addMethod($this_1, 'setGravity', setGravity$3, false);
function setGravity$1_2(g) {
$this_1.gravity.set( 0, g, 0 );
}
$p.addMethod($this_1, 'setGravity', setGravity$1_2, false);
function setDrag$1(d) {
$this_1.drag = d;
}
$p.addMethod($this_1, 'setDrag', setDrag$1, false);
function tick$0() {
$this_1.$self.tick( 1 );
}
$p.addMethod($this_1, 'tick', tick$0, false);
function tick$1_2(t) {
$this_1.integrator.step( t );
    for (var i =  0;  i<$this_1.pulses.size();  ) {
var p =  $this_1.pulses.get(i);
      p.tick(t);
      if (p.isOn()) {
i++;
} else {
$this_1.pulses.remove(i);
}
}
    if ($this_1.pulses.size()!=0) for (var i =  $this_1.pulses.iterator();  i.hasNext();  ) {
var p =  (i.next());
      p.tick( t );
      if (!p.isOn()) i.remove();
}
}
$p.addMethod($this_1, 'tick', tick$1_2, false);
function makeParticle$4(mass, x, y, z) {
var p =  new Particle( mass );
    p.position.set( x, y, z );
    $this_1.particles.add( p );
    return p;
}
$p.addMethod($this_1, 'makeParticle', makeParticle$4, false);
function makeParticle2$4(mass, x, y, z) {
$this_1.$self.makeParticle(mass, x, y, z);
    return $this_1.particles.size()-1;
}
$p.addMethod($this_1, 'makeParticle2', makeParticle2$4, false);
function makeParticle$0_2() {
return $this_1.$self.makeParticle( 1.0, 0, 0, 0 );
}
$p.addMethod($this_1, 'makeParticle', makeParticle$0_2, false);
function makeSpring$5(a, b, ks, d, r) {
var s =  new Spring( a, b, ks, d, r );
    $this_1.springs.add( s );
    return s;
}
$p.addMethod($this_1, 'makeSpring', makeSpring$5, false);
function makeAttraction$4(first, b, k, minDistance) {
var m =  new Attraction( first, b, k, minDistance );
    $this_1.attractions.add( m );
    return m;
}
$p.addMethod($this_1, 'makeAttraction', makeAttraction$4, false);
function makeAttraction2$4(a, b, k, minDistance) {
$this_1.$self.makeAttraction(a, b, k, minDistance);
    return $this_1.attractions.size()-1;
}
$p.addMethod($this_1, 'makeAttraction2', makeAttraction2$4, false);
function replaceAttraction$2(i, m) {
$this_1.attractions.set( i, m );
}
$p.addMethod($this_1, 'replaceAttraction', replaceAttraction$2, false);
function addPulse$1(pu) {
$this_1.pulses.add(pu);
}
$p.addMethod($this_1, 'addPulse', addPulse$1, false);
function clear$0() {
$this_1.particles.clear();
    $this_1.springs.clear();
    $this_1.attractions.clear();
    $this_1.customForces.clear();
    $this_1.pulses.clear();
}
$p.addMethod($this_1, 'clear', clear$0, false);
function applyForces$0() {
if ( $this_1.gravity.mag() != 0 )
      {
for (var i =  $this_1.particles.iterator();  i.hasNext();  )
    {
var p =  i.next();
            if (p.isFree()) p.force.add( $this_1.gravity );
}
}

    var target =  new $p.PVector();
    for (var i =  $this_1.particles.iterator();  i.hasNext();  )
      {
var p =  i.next();
        if (p.isFree()) p.force.add( $p.PVector.mult(p.velocity, -$this_1.drag, target) );
}

    $this_1.$self.applyAll($this_1.springs);
    $this_1.$self.applyAll($this_1.attractions);
    $this_1.$self.applyAll($this_1.customForces);
    $this_1.$self.applyAll($this_1.pulses);
}
$p.addMethod($this_1, 'applyForces', applyForces$0, false);
function applyAll$1(forces) {
if( forces.size()!=0 ) for (var i =  forces.iterator();  i.hasNext();  ) (i.next()).apply();
}
$p.addMethod($this_1, 'applyAll', applyAll$1, false);
function clearForces$0() {
for (var i =  $this_1.particles.iterator();  i.hasNext();  ) (i.next()).force.set(0, 0, 0);
}
$p.addMethod($this_1, 'clearForces', clearForces$0, false);
function numberOfParticles$0() {
return $this_1.particles.size();
}
$p.addMethod($this_1, 'numberOfParticles', numberOfParticles$0, false);
function numberOfSprings$0() {
return $this_1.springs.size();
}
$p.addMethod($this_1, 'numberOfSprings', numberOfSprings$0, false);
function numberOfAttractions$0() {
return $this_1.attractions.size();
}
$p.addMethod($this_1, 'numberOfAttractions', numberOfAttractions$0, false);
function getParticle$1(i) {
return $this_1.particles.get( i );
}
$p.addMethod($this_1, 'getParticle', getParticle$1, false);
function getSpring$1(i) {
return $this_1.springs.get( i );
}
$p.addMethod($this_1, 'getSpring', getSpring$1, false);
function getAttraction$1(i) {
return $this_1.attractions.get( i );
}
$p.addMethod($this_1, 'getAttraction', getAttraction$1, false);
function addCustomForce$1(f) {
$this_1.customForces.add( f );
}
$p.addMethod($this_1, 'addCustomForce', addCustomForce$1, false);
function numberOfCustomForces$0() {
return $this_1.customForces.size();
}
$p.addMethod($this_1, 'numberOfCustomForces', numberOfCustomForces$0, false);
function getCustomForce$1(i) {
return $this_1.customForces.get( i );
}
$p.addMethod($this_1, 'getCustomForce', getCustomForce$1, false);
function removeCustomForce$1(i) {
return $this_1.customForces.remove( i );
}
$p.addMethod($this_1, 'removeCustomForce', removeCustomForce$1, false);
function removeParticle$1(i) {
$this_1.particles.remove( i );
}
$p.addMethod($this_1, 'removeParticle', removeParticle$1, false);
function removeParticle$1_2(p) {
$this_1.particles.remove( p );
}
$p.addMethod($this_1, 'removeParticle', removeParticle$1_2, false);
function removeSpring$1(i) {
return $this_1.springs.remove( i );
}
$p.addMethod($this_1, 'removeSpring', removeSpring$1, false);
function removeAttraction$1(i) {
return $this_1.attractions.remove( i );
}
$p.addMethod($this_1, 'removeAttraction', removeAttraction$1, false);
function removeAttraction$1_2(s) {
$this_1.attractions.remove( s );
}
$p.addMethod($this_1, 'removeAttraction', removeAttraction$1_2, false);
function removeSpring$1_2(a) {
$this_1.springs.remove( a );
}
$p.addMethod($this_1, 'removeSpring', removeSpring$1_2, false);
function removeCustomForce$1_2(f) {
$this_1.customForces.remove( f );
}
$p.addMethod($this_1, 'removeCustomForce', removeCustomForce$1_2, false);
function $constr_2(g, somedrag){
$superCstr();

$this_1.$self.setGravity( 0, g, 0 );
    $this_1.drag = somedrag;
    $this_1.integrator = new RungeKuttaIntegrator( $this_1.$self );
}

function $constr_4(gx, gy, gz, somedrag){
$superCstr();

$this_1.$self.setGravity( gx, gy, gz );
    $this_1.drag = somedrag;
    $this_1.integrator = new RungeKuttaIntegrator( $this_1.$self );
}

function $constr_0(){
$superCstr();

$this_1.$self.setGravity( 0, ParticleSystem.DEFAULT_GRAVITY, 0 );
    $this_1.drag = ParticleSystem.DEFAULT_DRAG;
    $this_1.integrator = new RungeKuttaIntegrator( $this_1.$self );
}

function $constr() {
if(arguments.length === 2) { $constr_2.apply($this_1, arguments); } else if(arguments.length === 4) { $constr_4.apply($this_1, arguments); } else if(arguments.length === 0) { $constr_0.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
ParticleSystem.RUNGE_KUTTA =  0;
ParticleSystem.MODIFIED_EULER =  1;
ParticleSystem.DEFAULT_GRAVITY =  0;
ParticleSystem.DEFAULT_DRAG =  0.001;
return ParticleSystem;
})();
$p.ParticleSystem = ParticleSystem;
var RungeKuttaIntegrator = (function() {
function RungeKuttaIntegrator() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.originalPositions =  new $p.ArrayList();
$this_1.originalVelocities =  new $p.ArrayList();
$this_1.k1Forces =  new $p.ArrayList();
$this_1.k1Velocities =  new $p.ArrayList();
$this_1.k2Forces =  new $p.ArrayList();
$this_1.k2Velocities =  new $p.ArrayList();
$this_1.k3Forces =  new $p.ArrayList();
$this_1.k3Velocities =  new $p.ArrayList();
$this_1.k4Forces =  new $p.ArrayList();
$this_1.k4Velocities =  new $p.ArrayList();
$this_1.s = null;
function allocateParticles$0() {
while( $this_1.s.particles.size() > $this_1.originalPositions.size() ) {
$this_1.originalPositions.add( new $p.PVector() );
    $this_1.originalVelocities.add( new $p.PVector() );
    $this_1.k1Forces.add( new $p.PVector() );
    $this_1.k1Velocities.add( new $p.PVector() );
    $this_1.k2Forces.add( new $p.PVector() );
    $this_1.k2Velocities.add( new $p.PVector() );
    $this_1.k3Forces.add( new $p.PVector() );
    $this_1.k3Velocities.add( new $p.PVector() );
    $this_1.k4Forces.add( new $p.PVector() );
    $this_1.k4Velocities.add( new $p.PVector() );
}
}
$p.addMethod($this_1, 'allocateParticles', allocateParticles$0, false);
function setIntermediate$2(forces, velocities) {
$this_1.s.applyForces();
    for (var i =  0;  i < $this_1.s.particles.size();  ++i )
      {
var p =  $this_1.s.particles.get( i );
  if ( p.isFree() )
    {
(forces.get( i )).set( p.force.x, p.force.y, p.force.z );
      (velocities.get( i )).set( p.velocity.x, p.velocity.y, p.velocity.z );
            p.force.set(0,0,0);
}
}
}
$p.addMethod($this_1, 'setIntermediate', setIntermediate$2, false);
function updateIntermediate$3(forces, velocities, multiplier) {
var holder =  new $p.PVector();

    for (var i =  0;  i < $this_1.s.particles.size();  ++i )
      {
var p =  $this_1.s.particles.get( i );
  if ( p.isFree() )
    {
var op =  ($this_1.originalPositions.get( i ));
            p.position.set(op.x, op.y, op.z);
            p.position.add($p.PVector.mult((velocities.get( i )), multiplier, holder));
      var ov =  ($this_1.originalVelocities.get( i ));
            p.velocity.set(ov.x, ov.y, ov.z);
            p.velocity.add($p.PVector.mult((forces.get( i )), multiplier/p.mass0, holder));
}
}
}
$p.addMethod($this_1, 'updateIntermediate', updateIntermediate$3, false);
function initialize$0() {
for (var i =  0;  i < $this_1.s.particles.size();  ++i )
      {
var p =  ($this_1.s.particles.get( i ));
  if ( p.isFree() )
    {
(($this_1.originalPositions.get( i ))).set( p.position.x, p.position.y, p.position.z );
      (($this_1.originalVelocities.get( i ))).set( p.velocity.x, p.velocity.y, p.velocity.z );
}
  p.force.set(0,0,0);
}
}
$p.addMethod($this_1, 'initialize', initialize$0, false);
function step$1(deltaT) {
$this_1.$self.allocateParticles();
    $this_1.$self.initialize();
    $this_1.$self.setIntermediate($this_1.k1Forces, $this_1.k1Velocities);
    $this_1.$self.updateIntermediate($this_1.k1Forces, $this_1.k1Velocities, 0.5*deltaT );
    $this_1.$self.setIntermediate($this_1.k2Forces, $this_1.k2Velocities);
    $this_1.$self.updateIntermediate($this_1.k2Forces, $this_1.k2Velocities, 0.5*deltaT );
    $this_1.$self.setIntermediate($this_1.k3Forces, $this_1.k3Velocities);
    $this_1.$self.updateIntermediate($this_1.k3Forces, $this_1.k3Velocities, deltaT );
    $this_1.$self.setIntermediate($this_1.k4Forces, $this_1.k4Velocities);

              for (var i =  0;  i < $this_1.s.particles.size();  ++i )
      {
var p =  $this_1.s.particles.get( i );
  p.age0 += deltaT;
  if ( p.isFree() )
    {
var holder =  ($this_1.k2Velocities.get( i ));
            holder.add($this_1.k3Velocities.get( i ));
            holder.mult(2.0);
            holder.add($this_1.k1Velocities.get( i ));
            holder.add($this_1.k4Velocities.get( i ));
            holder.mult(deltaT / 6.0);
            holder.add($this_1.originalPositions.get( i ));
            p.position.set(holder.x, holder.y, holder.z);

             holder = $this_1.k2Forces.get( i );
      holder.add($this_1.k3Forces.get( i ));
            holder.mult(2.0);
            holder.add($this_1.k1Forces.get( i ));
            holder.add($this_1.k4Forces.get( i ));
            holder.mult(deltaT / (6.0 * p.mass0 ));
            holder.add($this_1.originalVelocities.get( i ));
      p.velocity.set(holder.x, holder.y, holder.z);
}
}
}
$p.addMethod($this_1, 'step', step$1, false);
function $constr_1(s){
$superCstr();

$this_1.s = s;
}

function $constr() {
if(arguments.length === 1) { $constr_1.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(RungeKuttaIntegrator, Integrator);
RungeKuttaIntegrator.$interfaces = [Integrator];
return RungeKuttaIntegrator;
})();
$p.RungeKuttaIntegrator = RungeKuttaIntegrator;
var Spring = (function() {
function Spring() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.springConstant0 = 0;
$this_1.damping0 = 0;
$this_1.restLength0 = 0;
$this_1.one = null;
$this_1.b = null;
$this_1.on =  true;
function turnOff$0() {
$this_1.on = false;
}
$p.addMethod($this_1, 'turnOff', turnOff$0, false);
function turnOn$0() {
$this_1.on = true;
}
$p.addMethod($this_1, 'turnOn', turnOn$0, false);
function isOn$0() {
return $this_1.on;
}
$p.addMethod($this_1, 'isOn', isOn$0, false);
function isOff$0() {
return !$this_1.on;
}
$p.addMethod($this_1, 'isOff', isOff$0, false);
function getOneEnd$0() {
return $this_1.one;
}
$p.addMethod($this_1, 'getOneEnd', getOneEnd$0, false);
function getTheOtherEnd$0() {
return $this_1.b;
}
$p.addMethod($this_1, 'getTheOtherEnd', getTheOtherEnd$0, false);
function currentLength$0() {
return $this_1.one.distanceTo( $this_1.b );
}
$p.addMethod($this_1, 'currentLength', currentLength$0, false);
function restLength$0() {
return $this_1.restLength0;
}
$p.addMethod($this_1, 'restLength', restLength$0, false);
function strength$0() {
return $this_1.springConstant0;
}
$p.addMethod($this_1, 'strength', strength$0, false);
function setStrength$1(ks) {
$this_1.springConstant0 = ks;
}
$p.addMethod($this_1, 'setStrength', setStrength$1, false);
function damping$0() {
return $this_1.damping0;
}
$p.addMethod($this_1, 'damping', damping$0, false);
function setDamping$1(d) {
$this_1.damping0 = d;
}
$p.addMethod($this_1, 'setDamping', setDamping$1, false);
function setRestLength$1(l) {
$this_1.restLength0 = l;
}
$p.addMethod($this_1, 'setRestLength', setRestLength$1, false);
function apply$0() {
if ( $this_1.on && ( $this_1.one.isFree() || $this_1.b.isFree() ) )
      {
var dx =  $this_1.one.position.x - $this_1.b.position.x;
        var dy =  $this_1.one.position.y - $this_1.b.position.y;
        var dz =  $this_1.one.position.z - $this_1.b.position.z;
        var distance =  Math.sqrt(dx * dx + dy * dy + dz * dz);
        if (distance != 0) {
dx /= distance;
          dy /= distance;
          dz /= distance;
}
        var springForce =  -(distance - $this_1.restLength0) * $this_1.springConstant0;
        var vx =  $this_1.one.velocity.x - $this_1.b.velocity.x;
        var vy =  $this_1.one.velocity.y - $this_1.b.velocity.y;
        var vz =  $this_1.one.velocity.z - $this_1.b.velocity.z;
        var dampingForce =  -$this_1.damping0 * (dx * vx + dy * vy + dz * vz);
        var force =  springForce + dampingForce;
        dx *= force;
        dy *= force;
        dz *= force;

        if ( $this_1.one.isFree() ) {
$this_1.one.force.x += dx;
          $this_1.one.force.y += dy;
          $this_1.one.force.z += dz;
}
        if ( $this_1.b.isFree() ) {
$this_1.b.force.x += dx * -1;
          $this_1.b.force.y += dy * -1;
          $this_1.b.force.z += dz * -1;
}
}
}
$p.addMethod($this_1, 'apply', apply$0, false);
function setA$1(p) {
$this_1.one = p;
}
$p.addMethod($this_1, 'setA', setA$1, false);
function setB$1(p) {
$this_1.b = p;
}
$p.addMethod($this_1, 'setB', setB$1, false);
function $constr_5(A, B, ks, d, r){
$superCstr();

$this_1.springConstant0 = ks;
    $this_1.damping0 = d;
    $this_1.restLength0 = r;
    $this_1.one = A;
    $this_1.b = B;
}

function $constr() {
if(arguments.length === 5) { $constr_5.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(Spring, Force);
Spring.$interfaces = [Force];
return Spring;
})();
$p.Spring = Spring;
var Smoother = (function() {
function Smoother() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.a = 0;
$this_1.gain = 0;
$this_1.lastOutput = 0;
$this_1.input = 0;
function setSmoothness$1(smoothness) {
$this_1.a = -smoothness; $this_1.gain = 1.0 + $this_1.a;
}
$p.addMethod($this_1, 'setSmoothness', setSmoothness$1, false);
function setTarget$1(target) {
$this_1.input = target;
}
$p.addMethod($this_1, 'setTarget', setTarget$1, false);
function setValue$1(x) {
$this_1.input = x; $this_1.lastOutput = x;
}
$p.addMethod($this_1, 'setValue', setValue$1, false);
function getTarget$0() {
return $this_1.input;
}
$p.addMethod($this_1, 'getTarget', getTarget$0, false);
function tick$0() {
$this_1.lastOutput = $this_1.gain * $this_1.input - $this_1.a * $this_1.lastOutput;
}
$p.addMethod($this_1, 'tick', tick$0, false);
function getValue$0() {
return $this_1.lastOutput;
}
$p.addMethod($this_1, 'getValue', getValue$0, false);
function $constr_1(smoothness){
$superCstr();

$this_1.$self.setSmoothness(smoothness);  $this_1.$self.setValue(0.0);
}

function $constr_2(smoothness, start){
$superCstr();

$this_1.$self.setSmoothness(smoothness); $this_1.$self.setValue(start);
}

function $constr() {
if(arguments.length === 1) { $constr_1.apply($this_1, arguments); } else if(arguments.length === 2) { $constr_2.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(Smoother, Tickable);
Smoother.$interfaces = [Tickable];
return Smoother;
})();
$p.Smoother = Smoother;
var Smoother3D = (function() {
function Smoother3D() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.x0 = null;
$this_1.y0 = null;
$this_1.z0 = null;
function setXTarget$1(X) {
$this_1.x0.setTarget(X);
}
$p.addMethod($this_1, 'setXTarget', setXTarget$1, false);
function setYTarget$1(X) {
$this_1.y0.setTarget(X);
}
$p.addMethod($this_1, 'setYTarget', setYTarget$1, false);
function setZTarget$1(X) {
$this_1.z0.setTarget(X);
}
$p.addMethod($this_1, 'setZTarget', setZTarget$1, false);
function getXTarget$0() {
return $this_1.x0.getTarget();
}
$p.addMethod($this_1, 'getXTarget', getXTarget$0, false);
function getYTarget$0() {
return $this_1.y0.getTarget();
}
$p.addMethod($this_1, 'getYTarget', getYTarget$0, false);
function getZTarget$0() {
return $this_1.z0.getTarget();
}
$p.addMethod($this_1, 'getZTarget', getZTarget$0, false);
function setTarget$3(X, Y, Z) {
$this_1.x0.setTarget(X);
    $this_1.y0.setTarget(Y);
    $this_1.z0.setTarget(Z);
}
$p.addMethod($this_1, 'setTarget', setTarget$3, false);
function setValue$3(X, Y, Z) {
$this_1.x0.setValue(X);
    $this_1.y0.setValue(Y);
    $this_1.z0.setValue(Z);
}
$p.addMethod($this_1, 'setValue', setValue$3, false);
function setX$1(X) {
$this_1.x0.setValue(X);
}
$p.addMethod($this_1, 'setX', setX$1, false);
function setY$1(Y) {
$this_1.y0.setValue(Y);
}
$p.addMethod($this_1, 'setY', setY$1, false);
function setZ$1(Z) {
$this_1.z0.setValue(Z);
}
$p.addMethod($this_1, 'setZ', setZ$1, false);
function setSmoothness$1(smoothness) {
$this_1.x0.setSmoothness(smoothness);
    $this_1.y0.setSmoothness(smoothness);
    $this_1.z0.setSmoothness(smoothness);
}
$p.addMethod($this_1, 'setSmoothness', setSmoothness$1, false);
function tick$0() {
$this_1.x0.tick(); $this_1.y0.tick(); $this_1.z0.tick();
}
$p.addMethod($this_1, 'tick', tick$0, false);
function x$0() {
return $this_1.x0.getValue();
}
$p.addMethod($this_1, 'x', x$0, false);
function y$0() {
return $this_1.y0.getValue();
}
$p.addMethod($this_1, 'y', y$0, false);
function z$0() {
return $this_1.z0.getValue();
}
$p.addMethod($this_1, 'z', z$0, false);
function $constr_1(smoothness){
$superCstr();

$this_1.x0 = new Smoother(smoothness);
    $this_1.y0 = new Smoother(smoothness);
    $this_1.z0 = new Smoother(smoothness);
}

function $constr_4(initialX, initialY, initialZ, smoothness){
$superCstr();

$this_1.x0 = new Smoother(smoothness, initialX);
    $this_1.y0 = new Smoother(smoothness, initialY);
    $this_1.z0 = new Smoother(smoothness, initialZ);
}

function $constr() {
if(arguments.length === 1) { $constr_1.apply($this_1, arguments); } else if(arguments.length === 4) { $constr_4.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendInterfaceMembers(Smoother3D, Tickable);
Smoother3D.$interfaces = [Tickable];
return Smoother3D;
})();
$p.Smoother3D = Smoother3D;
var Person = (function() {
function Person() {
var $this_1 = this;
var $super = { $upcast: $this_1 };
function $superCstr(){Item.apply($super,arguments);if(!('$self' in $super)) $p.extendClassChain($super)}
$this_1.yearOfBirth = 0;
$this_1.showsBeenIn = 0;
$this_1.count = 0;
$this_1.c = 0x00000000;
function find$2(s, showList) {
for (var i =  0;  i < showList.size();  i++) {
if (s == ( showList.get(i)).id) {
return i;
}
}

        return -1;
}
$p.addMethod($this_1, 'find', find$2, false);
function getTotalShowsBeenIn$0() {
return $this_1.count;
}
$p.addMethod($this_1, 'getTotalShowsBeenIn', getTotalShowsBeenIn$0, false);
function isInShow$1(s) {
for (var i =  0;  i < $this_1.count;  i++) {
if ($this_1.showsBeenIn[i] == s) {
return true;
}
}
        return false;
}
$p.addMethod($this_1, 'isInShow', isInShow$1, false);
function $constr_5(id, name, yearOfBirth, shows, showList){
$superCstr();

$this_1.id = id;
        $this_1.name = name;
        $this_1.yearOfBirth = yearOfBirth;
        $this_1.count = 0;
        $this_1.showsBeenIn = $p.createJavaArray('int', [MAX_SHOWS]);

        var num =  0;

        for (var i =  0;  i < shows.length;  i++) {
num = $this_1.$self.find(shows[i].id, showList);

            if (num > -1) {
$this_1.showsBeenIn[$this_1.count] = num;
                $this_1.count++;
}
}
}

function $constr() {
if(arguments.length === 5) { $constr_5.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendStaticMembers(Person, Item);
Person.$base = Item;
return Person;
})();
$p.Person = Person;
var Show = (function() {
function Show() {
var $this_1 = this;
var $super = { $upcast: $this_1 };
function $superCstr(){Item.apply($super,arguments);if(!('$self' in $super)) $p.extendClassChain($super)}
$this_1.startYear = 0;
function $constr_3(id, name, startYear){
$superCstr();

$this_1.id = id;
        $this_1.name = name;
        $this_1.startYear = startYear;
}

function $constr() {
if(arguments.length === 3) { $constr_3.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendStaticMembers(Show, Item);
Show.$base = Item;
return Show;
})();
$p.Show = Show;
var Vertex = (function() {
function Vertex() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.item = null;
$this_1.edge = null;
$this_1.numberOfEdges = 0;
$this_1.p = null;
$this_1.x = 0;
$this_1.y = 0;
$this_1.newX = 0;
$this_1.newY = 0;
function addEdge$1(e) {
$this_1.edge[$this_1.numberOfEdges] = e;
        $this_1.numberOfEdges++;
}
$p.addMethod($this_1, 'addEdge', addEdge$1, false);
function $constr_1(i){
$superCstr();

$this_1.item = i;

        $this_1.edge = $p.createJavaArray('Edge', [MAX_PEOPLE * MAX_SHOWS]);

        $this_1.x = $p.round($p.width / 2);
        $this_1.y = $p.round($p.height / 2);

        $this_1.newX = $this_1.x;
        $this_1.newY = $this_1.y;
}

function $constr() {
if(arguments.length === 1) { $constr_1.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
return Vertex;
})();
$p.Vertex = Vertex;
var MultiEdge = (function() {
function MultiEdge() {
var $this_1 = this;
var $super = { $upcast: $this_1 };
function $superCstr(){Edge.apply($super,arguments);if(!('$self' in $super)) $p.extendClassChain($super)}
$this_1.edges = null;
$this_1.numberOfEdges =  0;
$this_1.anim =  1.0;
$this_1.spring = null;
$this_1.colorMix = 0x00000000;
function addEdge$3(item, a, b) {
for (var i =  0;  i < $this_1.numberOfEdges;  i++) {
if ($this_1.edges[i].item.id == item.id) {
return;
}
}

        $this_1.edges[$this_1.numberOfEdges] = new Edge(item, a, b);
        $this_1.numberOfEdges++;

                          if ($p.__instanceof($this_1.edges[0].item , Person)) {
var hueTotal =  0;
            var satTotal =  0;
            var brightTotal =  0;
            var alphaTotal =  0;

            for    (var i =  0;  i < $this_1.numberOfEdges;  i++) {
hueTotal += $p.hue(( $this_1.edges[i].item).c);
                satTotal += $p.saturation(( $this_1.edges[i].item).c);
                brightTotal += $p.brightness(( $this_1.edges[i].item).c);
                alphaTotal += $p.alpha(( $this_1.edges[i].item).c);
}
            $p.colorMode($p.HSB);
            $this_1.colorMix = $p.color(hueTotal /  $this_1.numberOfEdges, satTotal /  $this_1.numberOfEdges, brightTotal /  $this_1.numberOfEdges, alphaTotal /  $this_1.numberOfEdges);
}
}
$p.addMethod($this_1, 'addEdge', addEdge$3, false);
function visibleItems$0() {
var visibleItems =  0;

        for (var i =  0;  i < $this_1.numberOfEdges;  i++) {
if ($this_1.edges[i].item.visible() == true) {
visibleItems++;
}
}

        return visibleItems;
}
$p.addMethod($this_1, 'visibleItems', visibleItems$0, false);
function $constr_3(i, a, b){
$superCstr(i, a, b);

        $this_1.edges = $p.createJavaArray('Edge', [$p.max(MAX_PEOPLE, MAX_SHOWS)]);
        $this_1.$self.addEdge(i, a, b);

        $this_1.item = null;
}

function $constr() {
if(arguments.length === 3) { $constr_3.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
$p.extendStaticMembers(MultiEdge, Edge);
MultiEdge.$base = Edge;
return MultiEdge;
})();
$p.MultiEdge = MultiEdge;
var Data = (function() {
function Data() {
var $this_1 = this;
function $superCstr(){$p.extendClassChain($this_1)}
$this_1.showList =  new $p.ArrayList();
$this_1.personList =  new $p.ArrayList();
function getShowList$0() {
return $this_1.showList;
}
$p.addMethod($this_1, 'getShowList', getShowList$0, false);
function getPersonList$0() {
return $this_1.personList;
}
$p.addMethod($this_1, 'getPersonList', getPersonList$0, false);
function countConnections$2(j, k) {
var c =  0;

        for (var i =  0;  i < $this_1.personList.size();  i++) {
if (( $this_1.personList.get(i)).isInShow(j) && ( $this_1.personList.get(i)).isInShow(k)) {
c++;
}
}

        return c;
}
$p.addMethod($this_1, 'countConnections', countConnections$2, false);
function $constr_0(){
$superCstr();

$this_1.showList.clear();
        $this_1.personList.clear();

                 for (var item  in  UsedData.show) {
$this_1.showList.add(new Show(UsedData.show[item].id, UsedData.show[item].title, UsedData.show[item].year));
}

        for (var item  in  UsedData.person) {
var getShows =  findShowsWithPersonIdFast(UsedData.person[item].id);
            $this_1.personList.add(new Person(UsedData.person[item].id, UsedData.person[item].name, UsedData.person[item].dob, getShows, $this_1.showList));
}
}

function $constr() {
if(arguments.length === 0) { $constr_0.apply($this_1, arguments); } else $superCstr();
}
$constr.apply(null, arguments);
}
return Data;
})();
$p.Data = Data;

var BORDER =  25;
var VERTEX_RADIUS_SCALE =  0.5;
var EDGE_THICKNESS_SCALE =  0.4;
var MOUSE_OVER_LINE_DISTANCE_THRESHOLD =  0.1;
var NEARNESS_THRESHOLD =  20.0;

var COLOR_EDGE_DEFAULT =  $p.color(64, 128, 187, 100 );
var COLOR_EDGE_AXES =  $p.color(127, 127, 127, 250 );
var COLOR_VERTEX_DEFAULT =  $p.color(64, 128, 187, 190);
var COLOR_VERTEX_HIGHLIGHT =  $p.color(64, 187, 128, 190);     var COLOR_VERTEX_DIM =  $p.color(64, 128, 187, 40);
var MAX_HUE =  235.0;         var font = null;
var fontBold = null;

var dragging =  false;
var draggedVertex =  -1;
var sortedPerson = 0;
var selectedPerson =  -1;

var MODE_PERSON_VERTICES =  0;
var MODE_SHOWS_VERTICES =  1;
var mode =  MODE_PERSON_VERTICES;

var LAYOUT_RANDOM_STATIC =  0;
var LAYOUT_RANDOM_AUTO =  1;
var LAYOUT_BY_DATE =  2;
var LAYOUT_BY_VALUE =  3;
var LAYOUT_BY_DATE_AND_VALUE =  4;
var layout =  LAYOUT_RANDOM_STATIC;

var EDGE_LENGTH =  400.0;
var EDGE_STRENGTH =  0.002;
var EDGE_DAMPING =  0.0002;
var SPACER_STRENGTH =  -10.0;
var MINIMUM_DISTANCE =  10.0;
var SPRING_LENGTH_NORMALISATION =  0.7;     var MASS_NORMALISATION =  0.2;              var RANDOM_MOVEMENT =  0.1;                 var physics = null;
var physicsEnabled =  false;

var MAX_PEOPLE =  64;
var MAX_SHOWS =  64;
var dataStore = null;
var show = null;
var person = null;
var vertices = null;
var edges = null;
var vertexCount =  0;
var edgeCount =  0;

function near(a, b) {
return $p.abs(a - b) < NEARNESS_THRESHOLD;
}
$p.near = near;
near = near.bind($p);

function resetData() {
dataStore = new Data();
}
$p.resetData = resetData;
resetData = resetData.bind($p);

function createGraph() {
mouseReleased();
    vertices = null;
    edges = null;
    vertices = $p.createJavaArray('Vertex', [$p.max(MAX_PEOPLE, MAX_SHOWS)]);
    edges = $p.createJavaArray('MultiEdge', [MAX_PEOPLE * MAX_SHOWS]);
    vertexCount = 0;
    edgeCount = 0;

    if (physics == null) {
physics = new ParticleSystem(0, 0.2);
}
    else {
physics.clear();
}

    show = dataStore.getShowList();
    person = dataStore.getPersonList();

    $p.colorMode($p.HSB);

    for (var j =  0;  j < person.size();  j++) {
( person.get(j)).c = $p.color(j * (MAX_HUE / person.size()), 128, 187, 100);
}

    if (mode == MODE_PERSON_VERTICES) {
for (var j =  0;  j < person.size();  j++) {
vertices[vertexCount] = new Vertex(person.get(j));
                         vertices[vertexCount].p = physics.makeParticle(1.0, vertices[vertexCount].x, vertices[vertexCount].y, 0);

            var i =  vertexCount;
            while (i > 0) {
physics.makeAttraction(vertices[i - 1].p, vertices[vertexCount].p, SPACER_STRENGTH, MINIMUM_DISTANCE);                         i--;
}

            vertexCount++;
}

        for (var j =  0;  j < show.size();  j++) {
for (var k =  0;  k < person.size();  k++) {
for (var l =  k + 1;  l < person.size();  l++) {
if (k != l && ((vertices[k].item)).isInShow(j) && ((vertices[l].item)).isInShow(j)) {
var e =  findEdge(vertices[k], vertices[l]);

                        if (e == null) {
edges[edgeCount] = new MultiEdge(show.get(j), vertices[k], vertices[l]);
                            edgeCount++;
}
                        else {
e.addEdge(show.get(j), vertices[k], vertices[l]);
}
}
}
}
}
}
    else {
for (var j =  0;  j < show.size();  j++) {
vertices[vertexCount] = new Vertex(show.get(j));
            vertices[vertexCount].p = physics.makeParticle(1.0, vertices[vertexCount].x, vertices[vertexCount].y, 0);

            var i =  vertexCount;
            while (i > 0) {
physics.makeAttraction(vertices[i - 1].p, vertices[vertexCount].p, SPACER_STRENGTH, MINIMUM_DISTANCE);                         i--;
}

            vertexCount++;
}
        for (var j =  0;  j < person.size();  j++) {
for (var k =  0;  k < show.size();  k++) {
for (var l =  k + 1;  l < show.size();  l++) {
var p =   person.get(j);

                    if (k != l && p.isInShow(k) && p.isInShow(l)) {
var e =  findEdge(vertices[k], vertices[l]);

                        if (e == null) {
edges[edgeCount] = new MultiEdge( person.get(j), vertices[k], vertices[l]);
                            edgeCount++;
}
                        else {
e.addEdge( person.get(j), vertices[k], vertices[l]);
}
}
}
}
}
}

    for (var j =  0;  j < edgeCount;  j++) {
edges[j].spring = physics.makeSpring(edges[j].vertexA.p, edges[j].vertexB.p, EDGE_STRENGTH * edges[j].numberOfEdges, EDGE_DAMPING, EDGE_LENGTH / (SPRING_LENGTH_NORMALISATION * $p.parseFloat(edges[j].numberOfEdges)));
}
    for (var j =  0;  j < vertexCount;  j++) {
vertices[j].p.setMass(MASS_NORMALISATION * $p.max(1, vertices[j].numberOfEdges));
}
}
$p.createGraph = createGraph;
createGraph = createGraph.bind($p);

 function layoutPosition(value, minimum, maximum, extent) {
if (minimum == maximum) {
return extent / 2.0;
}
    return BORDER + (extent - 2 * BORDER) * (value - minimum) / (maximum - minimum);
}
$p.layoutPosition = layoutPosition;
layoutPosition = layoutPosition.bind($p);

function setLayout() {
physicsEnabled = layout == LAYOUT_RANDOM_AUTO;
    $p.loop();
    if (vertexCount == 0) {
return;
}
    var minYear =  mode == MODE_PERSON_VERTICES ? getMinYearOfBirth() : getMinYear(show);
    var maxYear =  mode == MODE_PERSON_VERTICES ? getMaxYearOfBirth() : getMaxYear(show);
    var minValue =  getMinValue();
    var maxValue =  getMaxValue();
    var coincident =  true;
    for (var i =  1;  i < vertexCount;  i++) {
if ($p.dist(vertices[0].x, vertices[0].y, vertices[i].x, vertices[i].y) > 1) {
coincident = false;
            break;
}
}

    for (var j =  0;  j < vertexCount;  j++) {
var v =  vertices[j];
        if (physicsEnabled) {
if (coincident && vertexCount > 1) {
v.x = $p.random(BORDER, $p.width - BORDER);
                v.y = $p.random(BORDER, $p.height - BORDER);
}
            v.p.position.set(v.x, v.y, 0);
            v.p.velocity.set(0, 0, 0);
            continue;
}
        var itemYear =  mode == MODE_PERSON_VERTICES ? ( v.item).yearOfBirth : ( v.item).startYear;
        v.newX = $p.random(BORDER, $p.width - BORDER);
        v.newY = $p.random(BORDER, $p.height - BORDER);
        if (layout == LAYOUT_BY_DATE) {
v.newX = layoutPosition(itemYear, minYear, maxYear, $p.width);
} else if (layout == LAYOUT_BY_VALUE || layout == LAYOUT_BY_DATE_AND_VALUE) {
v.newX = layoutPosition(v.numberOfEdges, minValue, maxValue, $p.width);
}
        if (layout == LAYOUT_BY_DATE_AND_VALUE) {
v.newY = layoutPosition(itemYear, minYear, maxYear, $p.height);
}
}
}
$p.setLayout = setLayout;
setLayout = setLayout.bind($p);

 function getVertexCount() {
return vertexCount;
}
$p.getVertexCount = getVertexCount;
getVertexCount = getVertexCount.bind($p);
function getEdgeCount() {
return edgeCount;
}
$p.getEdgeCount = getEdgeCount;
getEdgeCount = getEdgeCount.bind($p);
function getVertex(index) {
return vertices[index];
}
$p.getVertex = getVertex;
getVertex = getVertex.bind($p);

function setViewMode(viewMode) {
mode = viewMode;
}
$p.setViewMode = setViewMode;
setViewMode = setViewMode.bind($p);

function resizePosition(value, oldExtent, newExtent) {
if (oldExtent <= 2 * BORDER) {
return newExtent / 2.0;
}
    return $p.constrain(BORDER + (value - BORDER) * (newExtent - 2 * BORDER) / (oldExtent - 2 * BORDER), BORDER, newExtent - BORDER);
}
$p.resizePosition = resizePosition;
resizePosition = resizePosition.bind($p);

function resizeGraph(graphWidth, graphHeight) {
graphWidth = $p.max(2 * BORDER + 1, graphWidth);
    graphHeight = $p.max(2 * BORDER + 1, graphHeight);
    if ($p.width == graphWidth && $p.height == graphHeight) {
return;
}
    var oldWidth =  $p.width;
    var oldHeight =  $p.height;
    mouseReleased();
    $p.size(graphWidth, graphHeight);
    $p.textFont(font);
    $p.textLeading(10);

    for (var i =  0;  i < vertexCount;  i++) {
var v =  vertices[i];
        v.x = resizePosition(v.x, oldWidth, $p.width);
        v.y = resizePosition(v.y, oldHeight, $p.height);
        v.newX = resizePosition(v.newX, oldWidth, $p.width);
        v.newY = resizePosition(v.newY, oldHeight, $p.height);
        v.p.position.set(v.x, v.y, 0);
        v.p.velocity.set(0, 0, 0);
}
    $p.loop();
}
$p.resizeGraph = resizeGraph;
resizeGraph = resizeGraph.bind($p);

function getMaxYearOfBirth() {
var max =  0;

    for (var i =  0;  i < person.size();  i++) {
var p =   person.get(i);
        if (p.yearOfBirth > max) {
max = p.yearOfBirth;
}
}

    return max;
}
$p.getMaxYearOfBirth = getMaxYearOfBirth;
getMaxYearOfBirth = getMaxYearOfBirth.bind($p);

function getMinYearOfBirth() {
var min =  $p.year();

    for (var i =  0;  i < person.size();  i++) {
var p =   person.get(i);
        if (p.yearOfBirth < min) {
min = p.yearOfBirth;
}
}

    return min;
}
$p.getMinYearOfBirth = getMinYearOfBirth;
getMinYearOfBirth = getMinYearOfBirth.bind($p);

function getMaxValue() {
var maxValue =  0;

    for (var j =  0;  j < vertexCount;  j++) {
if (vertices[j].numberOfEdges > maxValue) {
maxValue = vertices[j].numberOfEdges;
}
}

    return maxValue;
}
$p.getMaxValue = getMaxValue;
getMaxValue = getMaxValue.bind($p);

function getMinValue() {
var minValue =  getMaxValue();

    for (var j =  0;  j < vertexCount;  j++) {
if (vertices[j].numberOfEdges < minValue) {
minValue = vertices[j].numberOfEdges;
}
}

    return minValue;
}
$p.getMinValue = getMinValue;
getMinValue = getMinValue.bind($p);

function findEdge(a, b) {
for (var i =  0;  i < edgeCount;  i++) {
if ((edges[i].vertexA == a && edges[i].vertexB == b) || (edges[i].vertexA == b && edges[i].vertexB == a)) {
return edges[i];
}
}
    return null;
}
$p.findEdge = findEdge;
findEdge = findEdge.bind($p);

function changeLayoutMode(mode) {
if (mode >= 0 && mode <= 4) {
layout = mode;
        setLayout();
}
}
$p.changeLayoutMode = changeLayoutMode;
changeLayoutMode = changeLayoutMode.bind($p);

function mouseMoved() {
$p.loop();
}
$p.mouseMoved = mouseMoved;
mouseMoved = mouseMoved.bind($p);

function mouseOver() {
$p.loop();
}
$p.mouseOver = mouseOver;
mouseOver = mouseOver.bind($p);

function mouseOut() {
$p.loop();
}
$p.mouseOut = mouseOut;
mouseOut = mouseOut.bind($p);

function mouseDragged() {
$p.loop();
    if (draggedVertex < 0) {
return;
}
    dragging = true;
    var v =  vertices[draggedVertex];
    v.x = v.newX = $p.constrain($p.mouseX, BORDER, $p.width - BORDER);
    v.y = v.newY = $p.constrain($p.mouseY, BORDER, $p.height - BORDER);
    v.p.position.set(v.x, v.y, 0);
    v.p.velocity.set(0, 0, 0);
}
$p.mouseDragged = mouseDragged;
mouseDragged = mouseDragged.bind($p);

function mouseReleased() {
if (draggedVertex >= 0 && draggedVertex < vertexCount) {
vertices[draggedVertex].p.makeFree();
}
    dragging = false;
    draggedVertex = -1;
    $p.loop();
}
$p.mouseReleased = mouseReleased;
mouseReleased = mouseReleased.bind($p);

function mousePressed() {
$p.loop();
    if ($p.mouseButton != $p.LEFT) {
return;
}
    for (var i =  vertexCount - 1;  i >= 0;  i--) {
var v =  vertices[i];
        if ($p.dist(v.x, v.y, $p.mouseX, $p.mouseY) <= $p.max(6, v.numberOfEdges * VERTEX_RADIUS_SCALE)) {
draggedVertex = i;
            v.p.makeFixed();
            break;
}
}
}
$p.mousePressed = mousePressed;
mousePressed = mousePressed.bind($p);

function mouseIsOverLine(x1, y1, x2, y2) {
var d =  $p.dist(x1, y1, x2, y2);
    var d1 =  $p.dist(x1, y1, $p.mouseX, $p.mouseY);
    var d2 =  $p.dist(x2, y2, $p.mouseX, $p.mouseY);

         if (d1 < 25 || d2 < 25) {
return false;
}

         if (d1 + d2 < d + MOUSE_OVER_LINE_DISTANCE_THRESHOLD) {
return true;
}

    return false;
}
$p.mouseIsOverLine = mouseIsOverLine;
mouseIsOverLine = mouseIsOverLine.bind($p);

 function getConnections(j, k) {
var conn =  $p.createJavaArray('int', [MAX_PEOPLE]);
    var c =  0;

    for (var i =  0;  i < person.size();  i++) {
if (( person.get(i)).isInShow(j) && ( person.get(i)).isInShow(k)) {
conn[c] = i;
            c++;
}
}

    return conn;
}
$p.getConnections = getConnections;
getConnections = getConnections.bind($p);

function arrayFind(a, e) {
for (var i =  0;  i < a.length;  i++) {
if (a[i] == e) {
return true;
}
}

    return false;
}
$p.arrayFind = arrayFind;
arrayFind = arrayFind.bind($p);

function getMaxYear(show) {
var maxYear =  0;
    for (var i =  0;  i < show.size();  i++) {
maxYear = $p.max(maxYear, ( show.get(i)).startYear);
}
    return maxYear;
}
$p.getMaxYear = getMaxYear;
getMaxYear = getMaxYear.bind($p);

function getMinYear(show) {
var s = null;
    var minYear =  $p.year();

    for (var i =  0;  i < show.size();  i++) {
s = ( show.get(i));

        if (s.startYear <= minYear) {
minYear = s.startYear;
}
}

    return minYear;
}
$p.getMinYear = getMinYear;
getMinYear = getMinYear.bind($p);

function setup() {
$p.size(1200, 600);
    $p.smooth();

    $p.strokeWeight(4);
    font = $p.createFont("SansSerif.plain", 12);
    fontBold = $p.createFont("SansSerif.bold", 12);
    $p.textFont(font);
    $p.textLeading(10);
    $p.textAlign($p.CENTER);

         resetData();
    createGraph();
    setLayout();
}
$p.setup = setup;
setup = setup.bind($p);

function draw() {
var animating =  physicsEnabled && vertexCount > 0;
    if (physicsEnabled) {
physics.tick();

        for (var i =  0;  i < vertexCount;  ++i) {
var v =  vertices[i];
                         v.p.position.x = $p.constrain(v.p.position.x, BORDER, $p.width - BORDER);
            v.p.position.y = $p.constrain(v.p.position.y, BORDER, $p.height - BORDER);
            v.x = v.p.position.x;
            v.y = v.p.position.y;
}
}
    else {
for (var i =  0;  i < vertexCount;  ++i) {
if (!near(vertices[i].x, vertices[i].newX)) {
vertices[i].x += ((vertices[i].newX - vertices[i].x) / $p.__frameRate);
                animating = true;
}
            if (!near(vertices[i].y, vertices[i].newY)) {
vertices[i].y += ((vertices[i].newY - vertices[i].y) / $p.__frameRate);
                animating = true;
}
}
}

    $p.colorMode($p.HSB);
    $p.background(0);             $p.textAlign($p.RIGHT);

         $p.stroke(COLOR_EDGE_AXES);
    $p.strokeWeight(3);
    $p.fill(COLOR_EDGE_AXES);

    if (layout == LAYOUT_BY_VALUE) {
$p.line(25, 25, 225, 25);
        $p.line(225, 25, 220, 20);
        $p.line(225, 25, 220, 30);
        $p.text("size", 220, 40);
}
    else if (layout == LAYOUT_BY_DATE) {
$p.line(25, 25, 225, 25);
        $p.line(225, 25, 220, 20);
        $p.line(225, 25, 220, 30);
        $p.text("year", 220, 40);
}
    else if (layout == LAYOUT_BY_DATE_AND_VALUE) {
$p.line(25, 25, 225, 25);
        $p.line(225, 25, 220, 20);
        $p.line(225, 25, 220, 30);
        $p.text("size", 220, 40);

        $p.line(25, 25, 25, 225);
        $p.line(25, 225, 20, 220);
        $p.line(25, 225, 30, 220);
        $p.text("year", 60, 220);
}

         $p.stroke(COLOR_EDGE_DEFAULT);
    $p.strokeWeight(1);
    $p.colorMode($p.HSB);

    for (var k =  0;  k < edgeCount;  k++) {
if (edges[k].vertexA.item.visible() && edges[k].vertexB.item.visible()) {
if (mouseIsOverLine(edges[k].vertexA.x, edges[k].vertexA.y, edges[k].vertexB.x, edges[k].vertexB.y)) {
if (edges[k].anim < 21.0) {
edges[k].anim = edges[k].anim + 5.0;
                    animating = true;
}
                else {
edges[k].anim = 21.0;
}

                drawEdge(edges[k], edges[k].vertexA, edges[k].vertexB, edges[k].anim, true);
}
            else {
if (edges[k].anim > 1.0) {
edges[k].anim = edges[k].anim - 5.0;
                    animating = true;
}
                else {
edges[k].anim = 1.0;
}

                if (edges[k].anim == 1.0) {
if (mode == MODE_SHOWS_VERTICES) {
$p.stroke(edges[k].colorMix);
}
                    $p.strokeWeight( (edges[k].numberOfEdges * edges[k].numberOfEdges * EDGE_THICKNESS_SCALE));                      $p.line(edges[k].vertexA.x, edges[k].vertexA.y, edges[k].vertexB.x, edges[k].vertexB.y);
}
                else {
drawEdge(edges[k], edges[k].vertexA, edges[k].vertexB, edges[k].anim, false);
}
}
}
}

         $p.colorMode($p.RGB);
    $p.textAlign($p.LEFT);
    $p.textFont(font);

    for (j = 0;  j < vertexCount;  j++) {
$p.noStroke();

                 var radi =  $p.max(5, vertices[j].numberOfEdges * VERTEX_RADIUS_SCALE);
        var diam =  radi * 2.0;

        if (j == draggedVertex || $p.dist(vertices[j].x, vertices[j].y, $p.mouseX, $p.mouseY) < radi) {
$p.fill(COLOR_VERTEX_HIGHLIGHT);
}
        else {
$p.colorMode($p.RGB);
                         if ($p.__instanceof(vertices[j].item , Person)) {
$p.fill(( vertices[j].item).c);
}
            else {
$p.fill(COLOR_VERTEX_DEFAULT);
}
}

        if (selectedPerson == -1 || (selectedPerson > -1 && arrayFind(getConnections(j, j), selectedPerson))) {
$p.ellipse(vertices[j].x, vertices[j].y, diam, diam);
            $p.text(vertices[j].item.name, vertices[j].x + 2, vertices[j].y - 5 - radi);
}
        else {
$p.fill(COLOR_VERTEX_DIM);
            $p.ellipse(vertices[j].x, vertices[j].y, diam, diam);
            $p.text(vertices[j].item.name, vertices[j].x + 2, vertices[j].y - 5 - radi);
}
}

         if (!animating) {
$p.noLoop();
}
}
$p.draw = draw;
draw = draw.bind($p);

function drawEdge(e, v1, v2, distance, drawNames) {
var mid =  e.visibleItems() / 2.0;
    var col =  $p.color(0);

    var xm =  0.0;
    var ym =  0.0;
    var x1 =  0.0;
    var y1 =  0.0;
    var x2 =  0.0;
    var y2 =  0.0;
    var xoffset =  0.0;
    var yoffset =  0.0;

    if (v1.x == v2.x) {
xm = v1.x;
}
    else if (v1.x < v2.x) {
xm = v1.x + ((v2.x - v1.x) / 2);
}
    else if (v1.x > v2.x) {
xm = v2.x + ((v1.x - v2.x) / 2);
}
    if (v1.y == v2.y) {
ym = v1.y;
}
    else if (v1.y < v2.y) {
ym = v1.y + ((v2.y - v1.y) / 2);
}
    else if (v1.y > v2.y) {
ym = v2.y + ((v1.y - v2.y) / 2);
}

    var th =  $p.acos( $p.dist(v1.x, v1.y, v1.x, v2.y) / $p.dist(v1.x, v1.y, v2.x, v2.y) );

    if (v1.x < v2.x && v1.y < v2.y) {
th = $p.TWO_PI - th;
}

    for (var n =  0;  n < e.numberOfEdges;  n++) {
if (mode == MODE_SHOWS_VERTICES) {
col = ( e.edges[n].item).c;
}

                 if (e.visibleItems() > 1) {
xoffset = (( (n)) + 0.5 - mid) * $p.cos(th) * distance;
            yoffset = (( (n)) + 0.5 - mid) * $p.sin(th) * distance;
}

        $p.noFill();

        if (drawNames) {
$p.strokeWeight(4);
}
        else {
$p.strokeWeight(1);
}

        if ($p.__instanceof(e.edges[n].item , Show)) {
$p.colorMode($p.RGB);
            $p.stroke(COLOR_EDGE_DEFAULT);
            $p.colorMode($p.HSB);
}
        else if ($p.__instanceof(e.edges[n].item , Person)) {
$p.stroke(col);
}

        $p.bezier( v1.x, v1.y,
        xm + xoffset, ym + yoffset,
        xm + xoffset, ym + yoffset,
        v2.x, v2.y);

        if (drawNames) {
if ($p.__instanceof(e.edges[n].item , Person)) {
$p.fill(col);
}
            $p.text(e.edges[n].item.name, xm + xoffset, ym + yoffset);
}
}
}
$p.drawEdge = drawEdge;
drawEdge = drawEdge.bind($p);

}));
sketch.options.pauseOnBlur = true;
sketch.options.globalKeyEvents = false;
sketch.options.crisp = "false";
return sketch;
})(Processing.Sketch));
